// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD88nLhGMYswoYGt-YTdDP-tUFtiYqNqhI',
    appId: '1:238200191440:android:b4affe452b0133cdf8e1d5',
    messagingSenderId: '238200191440',
    projectId: 'todo-with-chat-functionality',
    databaseURL: 'https://todo-with-chat-functionality-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-with-chat-functionality.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcTZzvmRmFRyp0tnk9AdA52dw6q6sViw4',
    appId: '1:238200191440:ios:02bea0cb36846109f8e1d5',
    messagingSenderId: '238200191440',
    projectId: 'todo-with-chat-functionality',
    databaseURL: 'https://todo-with-chat-functionality-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-with-chat-functionality.appspot.com',
    iosClientId: '238200191440-te75a8h1rago8lv32art7dekd9cb8aru.apps.googleusercontent.com',
    iosBundleId: 'com.example.collaborativeTodoWithChatFeature',
  );
}
